name: Build and Deploy gh-pages

on:
  push:
    branches: [alternative-implementation]

jobs:
  build:
    name: Build gh-pages
    env:
      my_secret: ${{ secrets.COMMIT_SECRET }}
    runs-on: ubuntu-latest
    steps:
      - name: Clone flutter repository with master channel
        uses: subosito/flutter-action@v1
      
      - name: Run flutter doctor
        run: flutter doctor -v
      
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Change directory
        working-directory: example
        run: flutter pub get
      
      - name: Creating release build of web
        working-directory: example
        run: flutter build web --release
      
      - name: Pushing the release build
        working-directory: example/build/web
        run: |
          git init
          git config --global user.email aniketambore0@gmail.com
          git config --global user.name aniketambore
          git remote add origin https://${{ secrets.COMMIT_SECRET }}@github.com/aniketambore/bitcoinuikit-flutter.git
          git checkout -b gh-pages
          git add .
          git commit -m "${{ github.event.head_commit.message }}"
          git push origin gh-pages -f